### ISSUE TITLE
python: code analysis

### ISSUE THREAD

**Issue by AlexanderLanin** [eclipse-score/score#184]
# Provide Python Code Analysis Tooling

* [x] **Tool Selection**: Provide a basis for the decision on the tool(s) to use, considering performance, ease of use, compatibility with Bazel, and developer experience. Include tools like `ruff` (linter), `pyright` (type checker), and `beartype` (runtime type checker) in the evaluation. -> #259 
* [ ] **Stakeholders**: Investigate if there is a "Python expert group" or similar authority that must be consulted. If no formal group exists, gather feedback from team members actively working with Python.
* [ ] **Integration**: Integrate chosen tools into Bazel for consistency with the project's build system. Ensure seamless integration with VS Code, matching the experience as if Bazel were not used.
* [ ] **Configuration**: Define and provide reasonable initial configurations for the tools, balancing strictness with usability to minimize developer frustration while ensuring code quality.
* [ ] **Automation**: Set up GitHub Actions to enforce the usage of these tools, especially with checks on pull requests.
* [ ] **Documentation**: Create an onboarding guide for developers unfamiliar with the tools, covering setup, usage, and troubleshooting tips.

**Comment by hoe-jo** [comment]
We should evaluate ruff vs pylint. Ruff is generally faster but is lacking sopme checks, maybe we should evaluate this as well

**Comment by sameer6989** [comment]
We can use the below as a starting point to weigh the pros and cons of the various tools being suggested.

**Python code analysis tooling: Comparative evaluation**

----------

#### **1. Ruff (Linter)**

-   **Pros**:
    -   Extremely fast as it is written in Rust.
    -   Supports most common linting rules and auto-fix functionality.
    -   Minimal configuration required.
    -   Good integration with VS Code and Bazel.
-   **Cons**:
    -   Limited configurability compared to pylint.
    -   Does not yet cover all rules from Flake8 or pylint.

#### **2. Pylint (Linter)**

-   **Pros**:
    -   Highly configurable and enforces strict coding standards.
    -   Provides detailed messages for each issue found.
    -   Covers a broader set of linting rules than Ruff.
-   **Cons**:
    -   Slower than Ruff.
    -   Can be overly verbose with warnings.
    -   More configuration required for optimal performance.

#### **3. Black (Code formatter)**

-   **Pros**:
    -   Opinionated and enforces a single style, reducing code formatting discussions.
    -   Fast and easy to use.
    -   Strong compatibility with VS Code and Bazel.
-   **Cons**:
    -   No configurability; users must accept its formatting choices.
    -   Can make large diffs in repositories that previously used a different formatting style.

#### **4. Pyright (Type checker)**

-   **Pros**:
    -   Fast and supports large-scale projects efficiently.
    -   Deep integration with VS Code.
    -   Works well with gradual typing and Python type hints.
-   **Cons**:
    -   Some type-checking rules may be too strict for certain projects.
    -   Less extensive error explanations compared to mypy.

#### **5. Mypy (Type checker alternative to pyright)**

-   **Pros**:
    -   More established and widely used in Python static typing.
    -   Supports gradual typing and can catch complex type errors.
-   **Cons**:
    -   Slower than Pyright.
    -   Requires additional type annotations for full effectiveness.

#### **6. Beartype (Runtime type checker)**

-   **Pros**:
    -   Provides runtime type checking using decorators.
    -   Lightweight and efficient.
    -   Can complement static type checking for runtime validation.
-   **Cons**:
    -   Adds a performance overhead due to runtime checks.
    -   Not as widely adopted as static type checkers.
----------

### **Automation with GitHub Actions**

To enforce the usage of these tools, configure GitHub Actions:

#### **1. Setup workflow**

Create a `.github/workflows/code_analysis.yml` file: (sample code below)

```yaml
name: Code Analysis
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install ruff black # Install the agreed upon tools

      - name: Run Ruff
        run: ruff .
 
      - name: Run Black (Check Mode)
        run: black . --diff --color

```

#### **2. Enforcing checks**

-   Configure branch protection rules to require GitHub Actions checks to pass before merging.
----------
**References**:
-   [Ruff Documentation](https://beta.ruff.rs/docs/)
-   [Pylint Documentation](https://pylint.pycqa.org/)
-   [Black Documentation](https://black.readthedocs.io/)
-   [Pyright Documentation](https://microsoft.github.io/pyright/#/)
-   [Mypy Documentation](http://mypy-lang.org/)
-   [Beartype Documentation](https://beartype.readthedocs.io/)
