### ISSUE TITLE
docs: convert metamodel to yaml

### ISSUE THREAD

**Issue by AlexanderLanin** [eclipse-score/score#286]
Currently `docs/_tooling/extensions/score_metamodel/metamodel.py` contains only configuration, there is really no benefit in having it as python code.

Task:
* Convert from `py` to `yaml`
* Allow comments in yaml! (This means you cannot naivly use `yaml` package)
* Provide content to sphinx_needs in `setup()` of `score_metamodel`

Proposed scope of this first task, so we don't need to change the entire yaml twice:
* needs_extra_options can be computed from the other existing fields (set of all required options)
* links should be a dict and not a list.... e.g.:
```
needs_extra_links:
  contains:
    incoming: is part of
    outgoing: consists of
  responsible:
    incoming: is responsible for
    outgoing: responsible
```
* Same for needs_types:
```
types:
  workproduct:
    title: Workproduct
    prefix: WP__
    color: "#DDDD00" # yellow
    style: artifact
    mandatory_options:
      id: ^WP_.*$
      status: ^(draft|valid|invalid|volatile)$
      tags: ^.*$
      relevant: ^.*$
    mandatory_links:
      compliance-wp: ^.*$
```
* In needs_types split mandatory_options and mandatory_links (see above)
* Provide schema.json. It can be referenced from yaml via `# yaml-language-server: $schema=./metamodel-schema.json`

Future, out of scope for now:
* Default-values for e.g. status? References as in schema.json?
* Replace regex with e.g. enums?
* For links replace regex with the directive that is being linked
* Include Prefix definition in ID check so that ducplicate definition can be removed
