### ISSUE TITLE
reusable github workflows/actions

### ISSUE THREAD

**Issue by AlexanderLanin** [eclipse-score/score#512]
We'll have to define what exactly is reusable after we have 1-2 modules that use workflows, so we can see what the common parts are.

Make sure template repository is using the selected appoach.

**Comment by dcalavrezo-qorix** [comment]
A possible approach would be:


1. Create a centralized repository (github-actions-templates) to store reusable workflows.

2. Define workflows for linting, static analysis, unit testing, documentation, etc  in .github/workflows/.

3. Reference these workflows in each module repository using 
```
uses: org-name/github-actions-templates/.github/workflows/<workflow>.yml@v1.0.0.
```
5. Version control the workflows using tags (v1.0.0, v1.1.0), a stable branch, or commit SHAs for strict versioning.

7. Enforce usage through branch protection rules.

9. Nice to have: automate updates with Dependabot to notify repositories of new workflow versions ( on second thought maybe it doesn't make much sense for automotive projects)

**Comment by dcalavrezo-qorix** [comment]
Another thing that we should consider is to categorize modules based on ASIL levels -  even at GitHub actions level, meaning that we should have different workflows accordingly. 

This would involve specifying the ASIL level in each repo and dynamically selecting the appropriate workflows.

In the repo template we should add a configuration file, such as  `.github/asil-config.yml`, specifying the ASIL level

```yaml
asil_level: "B"
```

The next step would be to define reusable workflows for each ASIL class. I the centralized repo ( `github-actions-templates`) we should have differentiated workflows for each ASIL level.

We could different workflows for ASIL A, B, C, and D, adjusting:

- Code coverage thresholds
- Static analysis strictness
- Additional verification steps


Then in the repo we could add conditional workflow execution based on ASIL level

```yaml
run-workflows:
    needs: load-asil-config
    uses: eclipse-score/github-actions-templates/.github/workflows/static-analysis-asil-${{ needs.load-asil-config.outputs.asil_level }}.yml@v1.0.0
```


Example of a workflow diffrentiation

<html>
<body>

ASIL Level | Static Analysis | Unit Tests | Code Coverage |
-- | -- | -- | -- 
A | Basic checks | Basic | No requirement
B | Clang-Tidy, MISRA | Full | 80%+ 
C | Clang-Tidy, MISRA, Polyspace | Full | 90%+
D | Clang-Tidy, MISRA, Polyspace, Model Checking | Full | 100% 


</body>
</html>

**Comment by dcalavrezo-qorix** [comment]
Another important point would be to differentiate based on source code type ( `C++`, `Rust`, `Rust & Mixed`)

**Comment by AlexanderLanin** [comment]
Sounds good. But we'll have to see how centralized those workflows can be in reality. i.e. do the modules really all follow the same patterns. Or do they have custom pre-build, mid-build and post-build scripts etc.
Regarding coverage: it usually needs to be measured on specified tests. e.g. one number for unit tests, one number for component tests, etc. So we'll need those levels and the modules will need to actually use those levels. Lots of open points :/

How about we simply start with docs & cleaning? We can do that after #241

**Comment by dcalavrezo-qorix** [comment]
Proposal - will be part of the `README.md`

# Reusable GitHub Actions Workflows

This repository contains **reusable GitHub Actions workflows** designed to standardize CI/CD processes across multiple repositories
in `SCORE`. 
These workflows integrate with **Bazel** and provide a consistent way to run **documentation builds, license checks, static analysis, unit tests, and copyright verification** ( will need to be updated)

## Available Workflows

| Workflow | Description |
|----------|------------|
| **Documentation Build** | Builds project documentation and deploys it to GitHub Pages |
| **License Check** | Verifies OSS licenses and compliance |
| **Static Code Analysis** | Runs Clang-Tidy, Clippy, Pylint, and other linters based on project type |
| **Unit Tests** | Executes unit tests using GoogleTest, Rust test, or pytest |
| **Copyright Check** | Ensures all source files have the required copyright headers |

---

##  Using the Workflows in Your Repository

To use a reusable workflow, create a workflow file inside **your repository** (e.g., `.github/workflows/ci.yml`) and reference the appropriate workflow from this repository.

### **1️ Documentation Build Workflow**
** Usage Example **
```yaml
name: Documentation CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    uses: eclipse-score/ci_cd_repo/.github/workflows/docs.yml@main
    with:
      retention-days: 3
```
This workflow:
✅ Builds project documentation  
✅ Uploads it as an artifact  
✅ Deploys it to **GitHub Pages** on push to `main`  

---

### **2️ License Check Workflow**
**Usage Example**
```yaml
name: License Check CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  license-check:
    uses: eclipse-score/ci_cd_repo/.github/workflows/license-check.yml@main
    with:
      repo-url: "${{ github.server_url }}/${{ github.repository }}"
      project-types: "cpp rust"
    secrets:
      gitlab-api-token: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
```
This workflow:
✅ Runs ** DASH license compliance checks** for **Rust, C++, and Python**  
✅ Uses the **organization secret** `ECLIPSE_GITLAB_API_TOKEN` by default for DASH reviews. 
✅ Comments results directly on the **Pull Request**  

---

### **3️ Static Code Analysis Workflow**
**Usage Example**
```yaml
name: Static Analysis CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    uses: eclipse-score/ci_cd_repo/.github/workflows/static-analysis.yml@main
    with:
      project-types: "cpp rust python"
```
This workflow:
✅ Runs **Clang-Tidy** for C++  
✅ Runs **Rust Clippy, Cargo Audit, and Cargo Geiger**  for Rust
✅ Runs **Pylint** for Python  

---

### **4️ Unit Tests Workflow**
**Usage Example**
```yaml
name: Unit Test CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: eclipse-score/ci_cd_repo/.github/workflows/unit-tests.yml@main
    with:
      project-types: "cpp rust"
```
This workflow:
✅ Runs **GoogleTest** for C++  
✅ Runs **Rust Unit Tests**  
✅ Runs **pytest** for Python  

---

### **5️ Copyright Check Workflow**
**Usage Example**
```yaml
name: Copyright Check CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  copyright-check:
    uses: eclipse-score/ci_cd_repo/.github/workflows/copyright.yml@main
```
This workflow:
✅ Runs a **Bazel-based copyright verification check**  
✅ Ensures all files have the required **Eclipse Foundation** copyright headers  

---

##  How to Update Workflows
Since these workflows are centralized, updates in the `ci_cd_repo` repository will **automatically apply to all repositories using them**. If you need a specific version, reference a **tagged release** instead of `main`:
```yaml
uses: eclipse-score/ci_cd_repo/.github/workflows/unit-tests.yml@v1.0.0
```

---



### **Summary**
✅ **Standardized** CI/CD workflows across all projects  
✅ **Reusable & Maintainable** with centralized updates  
✅ **Bazel-powered** for consistent testing & analysis  





## Dependency on `bazel_rules` Repository

These reusable workflows rely on **Bazel rules** from the [`bazel_rules`](https://github.com/eclipse-org/bazel_rules) repository. 
This repository contains **shared Bazel configurations, toolchains, and linting/testing rules** used across all projects.

### **How to Integrate `bazel_rules` in Your Repository**

To ensure that your repository can correctly execute **static analysis, unit tests and other Bazel-based workflows**, 
you must **declare `bazel_rules` as a dependency**.

### **1️ Add `bazel-rules` to `MODULE.bazel`**
Each repository should **declare `bazel_rules` as a dependency** in its `MODULE.bazel` file.

**Location:** `MODULE.bazel`
```starlark
bazel_dep(name = "bazel_rules", version = "1.0.0")
```

### **2️ Ensure Bazel Can Fetch `bazel_rules`**
If `bazel_rules` is not installed locally, Bazel needs to fetch it.

**Location:** `MODULE`
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_rules",
    urls = ["https://github.com/eclipse-score/bazel_rules/releases/download/v1.0.0/bazel_rules.tar.gz"],
    strip_prefix = "bazel_rules-1.0.0",
)
```

### **3️ Use Bazel Rules in `BUILD.bazel`**
Once `bazel_rules` is integrated, you can **load and use shared Bazel rules** for **static analysis, testing, and linting**.

#### **Example: Using Clang-Tidy for C++**
**Location:** `BUILD.bazel`
```starlark
load("@bazel_rules//linting:clang_tidy.bzl", "clang_tidy")

clang_tidy()
```

#### **Example: Running Rust Clippy**
```starlark
load("@bazel_rules//linting:rust_clippy.bzl", "rust_clippy")

rust_clippy()
```

#### **Example: Running Unit Tests**
```starlark
load("@bazel_rules//testing:googletest.bzl", "googletest")
load("@bazel_rules//testing:rust_test.bzl", "rust_test")

googletest()
rust_test()
```

### **4️ Run Bazel Locally**
Once `bazel-rules` is integrated, you can execute **the same commands locally as in GitHub Actions**.

#### **Run Static Analysis**
```bash
bazel run @bazel_rules//linting:clang_tidy  # C++
bazel run @bazel_rules//linting:rust_clippy  # Rust
bazel run @bazel_rules//linting:pylint  # Python
```

#### **Run Unit Tests**
```bash
bazel test @bazel_rules//testing:googletest  # C++
bazel test @bazel_rules//testing:rust_test  # Rust
bazel test @bazel_rules//testing:pytest  # Python
```

---
