### ISSUE TITLE
docs: implement general graph checks scheme

### ISSUE THREAD

**Issue by hoe-jo** [eclipse-score/score#527]
Currently all graph checks are implemented as a 1:1 solution in python.

Here it would be very helpful to have a more generalized approach which uses the already existing metamodel.yaml

A proposal for that could be that we add here a section which follows some scheme like:

```
graph checks
  safety_check:
    apply:
      include: "comp_req"
      condition:
        "safety != QM"
    check:
      relation: "satisfies"
      condition:
        and:
          - "safety != QM"
          - "status == valid"
```
